
[[centers]]
id = 5161
short_name = "niagara"
full_name = "Niagara Falls EC"
address = "2250 WHIRLPOOL ST., NIAGARA FALLS, NEW YORK 14305"

[[centers]]
id = 5022
short_name = "buffalo"
full_name = "Buffalo-Ft. Erie Enrollment Center"
address = "10 CENTRAL AVE, FORT ERIE, ONTARIO L2A6G6"

[[centers]]
id = 5027
short_name = "mississauga"
full_name = "Toronto Enrollment Center"
address = " 6301 Silver Dart Drive, Mississauga, ONTARIO L5P1B2"

[[centers]]
id = 5025
short_name = "ottawa"
full_name = "Ottawa International Airport"
address = "140 Thad Johnson Private, Ottawa, ONTARIO K1V0R4"

[[centers]]
id = 5020
short_name = "blane"
full_name = "Blaine NEXUS And FAST Enrollment Center"
address = "8115 Birch Bay Square St., BLAINE, WASHINGTON 98230"

[[centers]]
id = 5060
short_name = "warroad"
full_name = "Warroad Enrollment Center"
address = "41059 Warroad Enrollment Center, Warroad, MINNESOTA 56763"
